### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by alif** [adjavaherian/carrythenews#1]
Testing wasn't a requirement for this exercise, but please detail how you would test this app - include libraries, tools, etc. that would be used.

**Comment by adjavaherian** [comment]
Ya, we could write a couple specs for the back end and the front end.  Basically, I would write a Mocha spec to check the connection to Twitter and verify the expected event trigger.  We'd have to expose a public method on the app that allows you to connect and listen.  As per the client, we could use Karma to bootstrap another spec that either connects to the live API, or uses a mock API to test the front-end functionality.
