### ISSUE TITLE
HTML & CSS

### ISSUE THREAD

**Issue by alif** [adjavaherian/carrythenews#2]
Do you have preferred html templating or css compilation libraries? Could you demonstrate using them for this exercise?

**Comment by adjavaherian** [comment]
Using SASS, I could make this shit look like it was minted by the US gov't.  I would use Handlebars, Jade or Lodash templates if we really wanted a super simple template.  Realistically, as a long term solution we would probably want to use something like React JSX, which would provide a lot of flexibility in a fast, easy to use package.
